language: java
install: "chmod u+x publish-doco.sh"
script: "./publish-doco.sh"
notifications:
  email:
    recipients:
      - betfair-cougar-dev@googlegroups.com
    on_success: always
    on_failure: always
env:
 global:
   - "GITHUB_USER=eswdd"
#   - "GITHUB_PASSWORD=rubbish"
   - secure: "gr/2VX6NwBXMlMD8FiSsuJfHixC7jE6SiQLKAg4DTr2CzBKmmBGS28azZV2AAdZ9vvhZVuwr2m5+aoS8XVdOcxYfGcX7Ya67T26irDp7s6d13TnUBbJgv82zVEb0NobOjQxdgFlhy8/QBq1DF8kzjJM9f6gO0szKbkihlU0TycM="
