language: ruby
install: 
  - "chmod u+x publish-doco.sh"
script: "./publish-doco.sh"
notifications:
  email:
    recipients:
      - betfair-cougar-dev@googlegroups.com
    on_success: always
    on_failure: always
env:
 global:
   # GITHUB_USER
   - secure: "qAxcWKsRIbljHCeebA7F93ZBu1LeMBINX56Wn6tEhKpckkXl2qrzKYyND1wu38q3aljTMwK3YpaYU78fxzzP+zFl26gSAhCWLhOEXwTxkRyb5ghV7jtjTq1TJNA7jjEz7AQAIjQw2zI6xFIQmqJBSTmziKy5owwes/IrT82Z9tA="
   # GITHUB_PASSWORD
   - secure: "SLo8XjMP8KhbUjpOCBaAHAKFDKXmbfRtI9uUOXNg+q3kvPL3uts+ccwHO1RaWOrieBD8vHc1NfE6g5dtHjXo1I3FBrF3MaS5RZEGUOgaavxa6QVWRCrwwmr36djwbOj51qQWqgWP0mHiHa4GbV5hZTNGSwpaSrnQz5hHrUGvg30="
   # GIT_NAME
   - secure: "OJIz6nwoPnNBPme8mKcf/ZroeMPiUoh254E4P02o+l8CnSWhGfq5M340uSiGFmSX01/a5Y4Y7xFV9Hcw1DguhpAaH/daNtFnhbq8+oVEwAvTyxZ1BL5zzVgQ1AX6CVxIFPLPqlpzsOOoyXlAnAv4G3E9YJo301BzjgkL/8Ovswg="
   # GIT_EMAIL
   - secure: "eoKzr3ZfHvyT7vms0x3jamN/lbnWUuDqq1q6W14BGVM2sbQqMiSuSqz+F27gvnI852zeUHg/nvkyF6K75U+YwaFKozYxa1ZrHFOHWv6G/WKhFdhhTx3ELQA/qJGF8F3W6i3d/hFp67G/DzIsytl0uZ/PCofylad5B6hiFG/vB4g="
