language: java
install: "chmod u+x publish-doco.sh"
script: "./publish-doco.sh"
notifications:
  email:
    recipients:
      - betfair-cougar-dev@googlegroups.com
    on_success: always
    on_failure: always
env:
 global:
   # GITHUB_USER
   - secure: "qAxcWKsRIbljHCeebA7F93ZBu1LeMBINX56Wn6tEhKpckkXl2qrzKYyND1wu38q3aljTMwK3YpaYU78fxzzP+zFl26gSAhCWLhOEXwTxkRyb5ghV7jtjTq1TJNA7jjEz7AQAIjQw2zI6xFIQmqJBSTmziKy5owwes/IrT82Z9tA="
   - "GIT_NAME=Simon Matic Langford"
   - "GIT_EMAIL=simon@exemel.co.uk"
   # GITHUB_PASSWORD
   - secure: "fxJcSZ38RHN8JX+RQ5juS4Q+5HfuPHJAHE32H0+wfAd+EuO8f8e3+7paFfB9pV6JeHTuQWbpz4YBif3Ofw/JthoFn2WEBDktXjvEH3RKD1MOq16SXRjh/sZ75N6CDWDZzoqZ7WBdERbJiVHCB8jPZwka/bxH6pbUK+VbB5FQCjE="
