language: java
install: "chmod u+x publish-doco.sh"
script: "./publish-doco.sh"
notifications:
  email:
    recipients:
      - betfair-cougar-dev@googlegroups.com
    on_success: always
    on_failure: always
env:
 global:
   - "GITHUB_USER=eswdd"
#   - "GITHUB_PASSWORD=rubbish"
   - secure: "og6X1CDQ323xXUXWmOUp2TBaoZC4rkL0dnGVOW89mfbYBJCfwLuw1XjT+EO9v20I8Hu7yGQuYWtOHECY89/ZkkXu4/vvmx/+38HygSEJZ2hVMOo6ZZNV0gvideIjy0esfYfq/XfMHHw6BUR+3q02g0z0aHh+nE3T6npd3nUmX+k="
