language: java
install: "chmod u+x publish-doco.sh"
script: "./publish-doco.sh"
notifications:
  email:
    recipients:
      - betfair-cougar-dev@googlegroups.com
    on_success: always
    on_failure: always
env:
 global:
   - "GITHUB_USER=eswdd"
   - "GIT_NAME=Simon Matic Langford"
   - "GIT_EMAIL=simon@exemel.co.uk"
   - secure: "fxJcSZ38RHN8JX+RQ5juS4Q+5HfuPHJAHE32H0+wfAd+EuO8f8e3+7paFfB9pV6JeHTuQWbpz4YBif3Ofw/JthoFn2WEBDktXjvEH3RKD1MOq16SXRjh/sZ75N6CDWDZzoqZ7WBdERbJiVHCB8jPZwka/bxH6pbUK+VbB5FQCjE="
